# Effects:
# - checkouts the repo
# - exports env variables from .github/workflows/constants.env to
#   the environment variables of a job

name: "Checkout"
description: "Checkout the repo, export constants to env variables"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: cardinalby/export-env-action@v1
      with:
        envFile: './.github/workflows/constants.env'
        expand: true