name: buildAndDeploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    env:
      EXTENSION_DIR_PATH: 'extension'
      PACKED_ZIP_PATH: 'build/extension.zip'

      OFFLINE_CRX_PATH: 'build/extension.offline.crx'
      OFFLINE_CRX_ASSET_NAME: 'extension.offline.crx'

      OFFLINE_XPI_PATH: 'build/extension.offline.xpi'
      OFFLINE_XPI_ASSET_NAME: 'extension.offline.xpi'

      WEBSTORE_PUBLISHED_CRX_PATH: 'build/extension.webstore.crx'
      WEBSTORE_PUBLISHED_CRX_ASSET_NAME: 'extension.webstore.crx'

      DELAYED_CHROME_WEBSTORE_DEPLOY_TAG: 'deploy-to-chrome-webstore'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Pack directory
      id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: ${{ env.EXTENSION_DIR_PATH }}
        zipFilePath: ${{ env.PACKED_ZIP_PATH }}

    - name: Build crx
      id: buildCrx
      uses: cardinalby/webext-buildtools-chrome-crx-action@v2
      with:
        zipFilePath: ${{ env.PACKED_ZIP_PATH }}
        crxFilePath: ${{ env.OFFLINE_CRX_PATH }}
        privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

    - name: Fetch Google API access token
      id: gAccessToken
      uses: cardinalby/google-api-fetch-token-action@v1
      with:
        clientId: ${{ secrets.G_CLIENT_ID }}
        clientSecret: ${{ secrets.G_CLIENT_SECRET }}
        refreshToken: ${{ secrets.G_REFRESH_TOKEN }}

    - name: Upload to Google Web Store
      id: gWebStoreUpload
      uses: cardinalby/webext-buildtools-chrome-webstore-upload-action@master
      continue-on-error: true
      with:
        zipFilePath: ${{ env.PACKED_ZIP_PATH }}
        extensionId: ${{ secrets.G_EXTENSION_ID }}
        apiAccessToken: ${{ steps.gAccessToken.outputs.accessToken }}

    - name: Schedule delayed Google Web Store uploading/publishing
      if: steps.gWebStoreUpload.outputs.inReviewError == 'true'
      uses: cardinalby/schedule-job-action@v1
      with:
        ghToken: ${{ secrets.WORKFLOWS_TOKEN }}
        templateYmlFile: '.github-workflows-templates/delayedChromeWebStoreDeploy.yml'
        addTag: ${{ env.DELAYED_CHROME_WEBSTORE_DEPLOY_TAG }}
        copyEnvVariables: |
          EXTENSION_DIR_PATH
          PACKED_ZIP_PATH
          WEBSTORE_PUBLISHED_CRX_PATH
          WEBSTORE_PUBLISHED_CRX_ASSET_NAME

    - name: Abort on Google Web Store upload error
      if: "!steps.gWebStoreUpload.outputs.newVersion && steps.gWebStoreUpload.outputs.inReviewError != 'true'"
      run: exit 1

    - name: Publish at Google Web Store
      id: gWebStorePublish
      if: steps.gWebStoreUpload.outputs.newVersion
      uses: cardinalby/webext-buildtools-chrome-webstore-publish-action@master
      with:
        extensionId: ${{ secrets.G_EXTENSION_ID }}
        apiAccessToken: ${{ steps.gAccessToken.outputs.accessToken }}

    - name: Download published crx file
      id: gWebStoreDownloadCrx
      if: steps.gWebStorePublish.outcome == 'success'
      uses: cardinalby/webext-buildtools-chrome-webstore-download-crx-action@master
      with:
        extensionId: ${{ secrets.G_EXTENSION_ID }}
        crxFilePath: ${{ env.WEBSTORE_PUBLISHED_CRX_PATH }}

    - name: Deploy to Firefox Addons
      uses: cardinalby/webext-buildtools-firefox-addons-action@master
      with:
        zipFilePath: ${{ env.PACKED_ZIP_PATH }}
        extensionId: ${{ secrets.FF_EXTENSION_ID }}
        jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
        jwtSecret: ${{ secrets.FF_JWT_SECRET }}

    - name: Sign Firefox xpi for offline distribution
      id: ffSignXpi
      uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@master
      with:
        timeoutMs: 300000
        zipFilePath: ${{ env.PACKED_ZIP_PATH }}
        xpiFilePath: ${{ env.OFFLINE_XPI_PATH }}
        jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
        jwtSecret: ${{ secrets.FF_JWT_SECRET }}

    - name: Create Release
      id: createRelease
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload offline crx release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.createRelease.outputs.upload_url }}
        asset_path: ${{ steps.buildCrx.outputs.crxFilePath }}
        asset_name: ${{ env.OFFLINE_CRX_ASSET_NAME }}
        asset_content_type: application/x-chrome-extension

    - name: Upload webstore published crx release asset
      if: steps.gWebStoreDownloadCrx.outcome == 'success'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.createRelease.outputs.upload_url }}
        asset_path: ${{ steps.gWebStoreDownloadCrx.outputs.crxFilePath }}
        asset_name: ${{ env.WEBSTORE_PUBLISHED_CRX_ASSET_NAME }}
        asset_content_type: application/x-chrome-extension

    - name: Upload offline xpi release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.createRelease.outputs.upload_url }}
        asset_path: ${{ steps.ffSignXpi.outputs.xpiFilePath }}
        asset_name: ${{ env.OFFLINE_XPI_ASSET_NAME }}
        asset_content_type: application/x-xpinstall