name: buildAndDeploy

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2
      id: tagName
    - name: Build Crx
      id: build_crx
      uses: cardinalby/webext-buildtools-chrome-crx-action@v1
      with:
        extensionDir: 'extension'
        crxFilePath: 'build/extension.offline.crx'
        privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tagName.outputs.tag }}
        release_name: Release ${{ steps.tagName.outputs.tag }}
        body: Extension release
        draft: false
        prerelease: false
    - name: Upload Release Asset (crx)
      id: upload-release-asset-crx
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.build_crx.outputs.crxFilePath }}
        asset_name: extension.offline.crx
        asset_content_type: application/x-chrome-extension