# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: buildAndDeploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Build Crx
      id: build-crx
      uses: cardinalby/webext-buildtools-chrome-crx-action@master
      with:
        extensionDir: 'extension'
        crxFilePath: 'build/extension.offline.crx'
        privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Extension release
        draft: false
        prerelease: false
    - name: Upload Release Asset (crx)
      id: upload-release-asset-crx
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/extensionOffline.crx
        asset_name: extension.offline.crx
        asset_content_type: application/x-chrome-extension