# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run buildAll
      env:
        G_REFRESH_TOKEN: ${{secrets.G_REFRESH_TOKEN}}
        G_EXTENSION_ID: ${{secrets.G_EXTENSION_ID}}
        G_CLIENT_SECRET: ${{secrets.G_CLIENT_SECRET}}
        G_CLIENT_ID: ${{secrets.G_CLIENT_ID}}
        FF_EXTENSION_ID: ${{secrets.FF_EXTENSION_ID}}
        FF_OFFLINE_EXT_ID: ${{secrets.FF_OFFLINE_EXT_ID}}
        FF_JWT_ISSUER: ${{secrets.FF_JWT_ISSUER}}
        FF_JWT_SECRET: ${{secrets.FF_JWT_SECRET}}
