name: "test"
on:
  push:
    branches:
      - '*'

jobs:
  test:
    env:
      DELAYED_JOB_CHECKOUT_REF: '1.1.30'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout by tag
        id: checkoutTag
        uses: actions/checkout@v2
        with:
          ref: ${{ env.DELAYED_JOB_CHECKOUT_REF }}

      - name: Get checked out commit SHA
        id: getCommitSha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Out sha
        run: echo ${{ steps.getCommitSha.outputs.sha }}

      - id: getRelease
        uses: cardinalby/git-get-release-action@master
        continue-on-error: true
        with:
          commitSha: ${{ steps.getCommitSha.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Out release
        run: echo ${{ steps.getRelease.outputs.upload_url }}